[package]
name = "skunk"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.7.15"
pest_derive = "2.7.15"
lazy_static = "1.5.0"
rustyline = "15.0.0"
colored = "2.2.0"
sysinfo = "0.33.0"
uuid = { version = "1", features = ["v4"] }